name: ${project.artifactId}
main: ${mainClass}
version: ${project.version}
description: ${project.description}
author: kangarko
authors: [${authors}]
depend: [${hardDepend}]
softdepend: [${softDepend}]
commands: 
  chatcontrol:
    aliases: [ccontrol, chatc, chc]
    description: Main ChatControl command. Type /chatcontrol list for commands.
permissions:
    chatcontrol.notify.overrideranged:
        default: false
    chatcontrol.notify.whenmentioned:
        default: true
        description: Play sound to player when notified by another player and function is enabled.
    chatcontrol.broadcaster.view:
        default: true
        description: View timed messages from auto broadcaster.